package com.riskguard.transaction.config;

import jakarta.servlet.*; import jakarta.servlet.http.*; import java.io.IOException; import java.time.Duration; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.http.MediaType; import org.springframework.stereotype.Component; import org.springframework.web.filter.OncePerRequestFilter;

@Component public class RateLimitFilter extends OncePerRequestFilter {
 private final StringRedisTemplate redis; private final boolean enabled; private final long login,transaction,refresh,admin;
 public RateLimitFilter(StringRedisTemplate redis,@Value("${app.rate-limit.enabled:true}") boolean enabled,@Value("${app.rate-limit.login-per-minute:10}") long login,@Value("${app.rate-limit.transaction-per-minute:60}") long transaction,@Value("${app.rate-limit.refresh-per-minute:20}") long refresh,@Value("${app.rate-limit.admin-per-minute:30}") long admin){this.redis=redis;this.enabled=enabled;this.login=login;this.transaction=transaction;this.refresh=refresh;this.admin=admin;}
 @Override protected void doFilterInternal(HttpServletRequest req,HttpServletResponse res,FilterChain chain)throws IOException,ServletException{if(!enabled){chain.doFilter(req,res);return;}long limit=limit(req.getRequestURI(),req.getMethod());if(limit<=0){chain.doFilter(req,res);return;}String bucket=String.valueOf(System.currentTimeMillis()/60000);String key="riskguard:rate:"+bucket+":"+req.getRemoteAddr()+":"+req.getRequestURI();try{Long count=redis.opsForValue().increment(key);if(count!=null&&count==1)redis.expire(key,Duration.ofSeconds(65));if(count!=null&&count>limit){res.setStatus(429);res.setContentType(MediaType.APPLICATION_JSON_VALUE);res.setHeader("Retry-After","60");res.getWriter().write("{\"status\":429,\"code\":\"RATE_LIMITED\",\"message\":\"Too many requests\"}");return;}}catch(RuntimeException ignored){/* Redis unavailable: API remains available and source of truth stays PostgreSQL. */}chain.doFilter(req,res);}
 private long limit(String path,String method){if(path.endsWith("/auth/login"))return login;if(path.endsWith("/auth/refresh"))return refresh;if(path.startsWith("/api/v1/admin"))return admin;if(path.equals("/api/v1/transactions")&&"POST".equalsIgnoreCase(method))return transaction;return 0;}
}
