package com.riskguard.transaction.service;
import com.riskguard.transaction.api.dto.ReviewDtos; import com.riskguard.transaction.domain.*; import com.riskguard.transaction.repository.*; import java.math.BigDecimal; import java.time.Instant; import java.util.List; import java.util.Map; import java.util.UUID; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class FraudReviewService { private final FraudReviewRepository reviews; private final TransactionRepository transactions; private final UserRepository users; private final TransactionStatusHistoryRepository history; private final AuditService audit;
 public FraudReviewService(FraudReviewRepository r,TransactionRepository t,UserRepository u,TransactionStatusHistoryRepository h,AuditService a){reviews=r;transactions=t;users=u;history=h;audit=a;}
 @Transactional public ReviewDtos.Response review(UUID reviewerId,UUID transactionId,ReviewDtos.Create request,String correlationId){Transaction t=transactions.findById(transactionId).orElseThrow(()->new DomainExceptions.NotFound("Transaction not found")); if(t.getStatus()!=TransactionStatus.REVIEW)throw new DomainExceptions.Conflict("Only transactions in REVIEW can receive a manual decision"); UserAccount reviewer=users.findById(reviewerId).orElseThrow(()->new DomainExceptions.NotFound("Reviewer not found")); FraudDecision automatic=decisionFrom(t); BigDecimal original=t.getRiskScore()==null?BigDecimal.ZERO:t.getRiskScore(); Instant now=Instant.now(); TransactionStatus target=request.decision()==ReviewDecision.APPROVE?TransactionStatus.APPROVED:TransactionStatus.BLOCKED; FraudReview saved=reviews.save(new FraudReview(UUID.randomUUID(),t,reviewer,request.decision(),request.reason().trim(),automatic,original,correlationId,now)); t.changeStatus(target,now); transactions.saveAndFlush(t); history.save(new TransactionStatusHistory(UUID.randomUUID(),t,target,now,reviewer)); audit.record("FRAUD_REVIEW",reviewerId,correlationId,"TRANSACTION",transactionId,Map.of("status",TransactionStatus.REVIEW.name(),"riskScore",original),Map.of("status",target.name(),"reviewId",saved.getId().toString())); return toResponse(saved);}
 @Transactional(readOnly=true) public List<ReviewDtos.Response> list(UUID transactionId){return reviews.findAllByTransactionIdOrderByReviewedAtAsc(transactionId).stream().map(FraudReviewService::toResponse).toList();}
 private static FraudDecision decisionFrom(Transaction t){return switch(t.getStatus()){case APPROVED->FraudDecision.APPROVED;case BLOCKED->FraudDecision.BLOCKED;default->FraudDecision.REVIEW;};}
 private static ReviewDtos.Response toResponse(FraudReview r){return new ReviewDtos.Response(r.getId(),r.getTransaction().getId(),r.getReviewer().getId(),r.getDecision(),r.getReason(),r.getAutomaticDecision(),r.getOriginalRiskScore(),r.getCorrelationId(),r.getReviewedAt());}
}
